language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
    - chmod +x gradlew
before_script:
    - ./gradlew assemble
script:
    - ./gradlew test
